# Netlify config to enable serverless proxy functions
[build]
  functions = "netlify/functions"
  publish = "."  # adjust if your site root is different (e.g., "dist" or "public")

# Optional: prevent SPA rewrites from intercepting static assets (keeps .js/.css intact)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200
